### ISSUE TITLE
Mit Android 12 kein login mehr möglich 

### ISSUE THREAD

**Issue by sozifa** [sipgate-io/fax-sample-app#1]
Seit dem Update auf Android 12 bleibt die app beim login hängen

**Comment by sgeklorer** [comment]
I can confirm. Wanting to try out the app, I installed it on my phone and am unable to log in. The login page shows "no account with those credentials". This is with a Sipgate basic account. However, in my case, this was on a phone running Android 11.

**Comment by dknerr** [comment]
The login problem has been resolved with the latest commit. If you run into other problems, please feel free to open a new issue.

Best regards
Daniel from sipgate.io
